local M = require("nbin.mapping")

M.inoremap("<C-x>", "coc#refresh()", {silent = true, expr = true})
M.inoremap("<Cr>", "coc#pum#visible() ? coc#pum#confirm() : '<CR>'", {silent = true, expr = true})
M.inoremap("<Tab>", "coc#pum#visible() ? coc#pum#next(1) : '<Tab>'", {expr = true})
M.inoremap("<S-Tab>", "coc#pum#visible() ? coc#pum#prev(1) : '<S-Tab>'", {expr = true})
M.nnoremap("gd", ":call CocAction('jumpImplementation')<Cr>", {silent = true})
M.nnoremap("gy", ":call CocAction('jumpTypeDefinition')<Cr>", {silent = true})
M.nnoremap("<S-K>", ":call CocAction('doHover', v:false)<CR>", {silent = true})
M.nnoremap("<C-n>", ":call CocAction('diagnosticNext')<CR>", {silent = true})
M.nnoremap("<S-F>", ":call CocAction('doQuickfix')<CR>", {silent = true})
