local map = require("mapping")
local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

map.nnoremap("<leader>a", mark.add_file)
map.nnoremap("<leader>1", function ()
  ui.nav_file(1)
end)
map.nnoremap("<leader>2", function ()
  ui.nav_file(2)
end)
map.nnoremap("<leader>3", function ()
  ui.nav_file(3)
end)
map.nnoremap("<leader>4", function ()
  ui.nav_file(4)
end)
